name: Continuous Integration

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: submission-forum-api
          POSTGRES_DB: forumapitest_rudy
        options: >-
          --health-cmd "pg_isready -U postgres -d forumapitest_rudy" 
          --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install, Migrate & Test
        run: |
          npm install
          npm run migrate up
          npm run test
        env:
          CI: true
          HOST: localhost
          PORT: 3000

          # koneksi ke service postgres
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: submission-forum-api
          PGDATABASE: forumapitest_rudy

          # variabel khusus test, jika kode-mu membaca PG*_TEST
          PGHOST_TEST: localhost
          PGPORT_TEST: 5432
          PGUSER_TEST: postgres
          PGPASSWORD_TEST: submission-forum-api
          PGDATABASE_TEST: forumapitest_rudy

          # token secrets
          ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
          REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
          ACCESS_TOKEN_AGE: 3000
